version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: >
      sh -c "
      pip install -r requirements.txt &&
      python src/presentation/app/app.py
      "

volumes:
  mongo_data:
